### ISSUE TITLE
Can you upload the Pretrained model ?

### ISSUE THREAD

**Issue by PrideDream** [JiazhengLUO/CorrDGM#1]
First, thank you for your great work! It is really helpful.

1. Can you upload the Pretrained model ?
2. I find that data loading consumes CPU very much. I use ` torch.set_num_threads(1)` to limit CPU consumption. Do you have a better way?

Any help will be gratefully received.

**Comment by JiazhengLUO** [comment]
Hello, thanks for your  attention
1. The pretrained model have been uploaded, you can use it directly.
2.  Sorry, I am not very clear about the problem you encountered, please try to search for some solutions.
